### ISSUE TITLE
no macos support

### ISSUE THREAD

**Issue by charlesrocket** [cannabiscoindev/cannabiscoin420#10]
is there anybody who managed to get working binary on high sierra (10.13.4)?

**Comment by Bushstar** [comment]
There is a compiled binary available from the release tab, compiling your own on Mac is never the easiest especially with the Bitcoin 0.8 codebase on which this is based. The next version of Cannabiscoin will be based on the 0.13 codebase which will make compilation on Mac and other platforms a lot easier.
