### ISSUE TITLE
Mac Client Update?

### ISSUE THREAD

**Issue by djneely** [cannabiscoindev/cannabiscoin420#11]
Is there going to be a Mac client update soon? 

As of the maintenance period, I've lost (or not received) over 20 transactions from mining. Looking at the Blockchain explorer the payments were sent, my address should have ~164 CANN in it, however, the Mac wallet is only showing ~55.

I've since stopped mining CANN due to this issue.

Thoughts? Help?

**Comment by Bushstar** [comment]
There is now a new version of the Mac client available from the release tab on this repo.
