### ISSUE TITLE
? openssl 1.0.1 does not fix bignum error

### ISSUE THREAD

**Issue by movingelectrons** [cannabiscoindev/cannabiscoin420#12]
this seems to still be broken, I am running debian 9 and I installed openssl 1.0.1 following the second suggestion here: https://unix.stackexchange.com/questions/419714/debian-9-old-version-of-openssl IE creating the /etc/apt/sources.list.d/jessie.list file...

Preconfiguring packages ...
Selecting previously unselected package libssl1.0.0:amd64.
(Reading database ... 269193 files and directories currently installed.)
Preparing to unpack .../libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.1t-1+deb8u8) ...
Setting up libssl1.0.0:amd64 (1.0.1t-1+deb8u8) ...

jeromes@jtop ~/Downloads/cryptocoins/cannabiscoin420/src (master) $ make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
g++ -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/include -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2 -o CannabisCoind leveldb/libleveldb.a obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/keystore.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/hash.o obj/bloom.o obj/noui.o obj/leveldb.o obj/txdb.o obj/cubehash.o obj/luffa.o obj/aes_helper.o obj/echo.o obj/shavite.o obj/simd.o obj/blake.o obj/bmw.o obj/groestl.o obj/jh.o obj/keccak.o obj/skein.o obj/checkpointsync.o -Wl,-z,relro -Wl,-z,now -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/libleveldb.a /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/libmemenv.a
obj/key.o: In function SetSecretBytes': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to BN_init' obj/init.o: In functionAppInit2(boost::thread_group&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/init.cpp:658: undefined reference to SSLeay_version' obj/init.o: In functionCBigNum::CBigNum(std::vector<unsigned char, std::allocator > const&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:96: undefined reference to BN_init' obj/main.o: In functionCBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
obj/main.o: In function CBigNum::CBigNum(unsigned int)': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:89: undefined reference toBN_init'
obj/main.o: In function CBigNum::CBigNum()': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
obj/main.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: more undefined references to BN_init' follow obj/bitcoinrpc.o: In functionboost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
/usr/include/boost/asio/ssl/impl/context.ipp:125: undefined reference to SSLv23_method' /usr/include/boost/asio/ssl/impl/context.ipp:125: undefined reference toSSLv23_method'
obj/bitcoinrpc.o: In function boost::asio::ssl::detail::openssl_init_base::do_init::~do_init()': /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:72: undefined reference toCRYPTO_set_locking_callback'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:73: undefined reference to ERR_free_strings' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:74: undefined reference toEVP_cleanup'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:75: undefined reference to CRYPTO_cleanup_all_ex_data' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:84: undefined reference toSSL_COMP_free_compression_methods'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:92: undefined reference to ENGINE_cleanup' obj/bitcoinrpc.o: In functionCBigNum::CBigNum(int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference toBN_init'
obj/bitcoinrpc.o: In function CBigNum::CBigNum()': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
obj/bitcoinrpc.o: In function boost::asio::ssl::detail::openssl_init_base::do_init::~do_init()': /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:72: undefined reference toCRYPTO_set_locking_callback'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:73: undefined reference to ERR_free_strings' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:74: undefined reference toEVP_cleanup'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:75: undefined reference to CRYPTO_cleanup_all_ex_data' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:84: undefined reference toSSL_COMP_free_compression_methods'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:92: undefined reference to ENGINE_cleanup' obj/bitcoinrpc.o: In functionboost::asio::ssl::detail::openssl_init_base::do_init::do_init()':
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:39: undefined reference to SSL_library_init' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:40: undefined reference toSSL_load_error_strings'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:41: undefined reference to OPENSSL_add_all_algorithms_noconf' /usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:44: undefined reference toCRYPTO_num_locks'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:47: undefined reference to CRYPTO_set_locking_callback' obj/rpcdump.o: In functionCBigNum::CBigNum(int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference toBN_init'
obj/rpcdump.o: In function CBigNum::CBigNum()': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
obj/rpcdump.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: more undefined references to BN_init' follow obj/util.o: In functionCInit::~CInit()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:125: undefined reference to CRYPTO_set_locking_callback' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:126: undefined reference toCRYPTO_num_locks'
obj/util.o: In function CInit::CInit()': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:109: undefined reference toCRYPTO_num_locks'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:110: undefined reference to CRYPTO_num_locks' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:112: undefined reference toCRYPTO_set_locking_callback'
obj/crypter.o: In function CCrypter::Encrypt(std::vector<unsigned char, secure_allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&)': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:63: undefined reference toEVP_CIPHER_CTX_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:67: undefined reference to EVP_CIPHER_CTX_cleanup' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:67: undefined reference toEVP_CIPHER_CTX_cleanup'
obj/crypter.o: In function CCrypter::Decrypt(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, secure_allocator<unsigned char> >&)': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:90: undefined reference toEVP_CIPHER_CTX_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:94: undefined reference to EVP_CIPHER_CTX_cleanup' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:94: undefined reference toEVP_CIPHER_CTX_cleanup'
obj/rpcmining.o: In function CBigNum::CBigNum()': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to BN_init' /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference toBN_init'
obj/rpcwallet.o: In function CBigNum::CBigNum(int)': /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference toBN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to BN_init' obj/rpcwallet.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: more undefined references toBN_init' follow
collect2: error: ld returned 1 exit status
makefile.unix:186: recipe for target 'CannabisCoind' failed
make: *** [CannabisCoind] Error 1

**Comment by Bushstar** [comment]
Looks like it could be picking up the wrong version of OpenSSL. The new version of Cannabiscoin will be based on Bitcoin 0.13 and will come with a depends folder containing all the required dependencies to compile the client on all platforms. It will make compilation a lot easier than it is now.
