### ISSUE TITLE
Project Alive, Project Dead?

### ISSUE THREAD

**Issue by AlexanderPeters** [cannabiscoindev/cannabiscoin420#13]
Hi, all I'd love to help contribute to this community and help us build this coin back up to it's former glory. But, I can't really tell what state the coin is in. So please let me know if this project is alive, dead, or slowly dying and fading away although still functional. Thanks

**Comment by cannabiscoindev** [comment]
Please email support@cannabiscoin.net and include your Discord ID so we can discuss

**Comment by AlexanderPeters** [comment]
Hi, I emailed you all but, have yet to receive a response. Is there a reason for this?

**Comment by thor901** [comment]
the project is dead????
