### ISSUE TITLE
Windows 0.8.9 Update - GUI Never Shows

### ISSUE THREAD

**Issue by djneely** [cannabiscoindev/cannabiscoin420#14]
Seems to be an odd issue with the Windows 0.8.9 update. After launching the application the app goes into the taskbar but you're unable to actually show the wallet. After upgrading from 0.8.8 to 0.8.9 I had to revert back to 0.8.8 to use the wallet.

**Comment by Bushstar** [comment]
I'll do a clean build and post the binary again for Windows again, will post back here when completed.

**Comment by Bushstar** [comment]
Please download the binary and try again.

https://github.com/cannabiscoindev/cannabiscoin420/releases/tag/v0.8.9.0

**Comment by djneely** [comment]
That did the trick. Thanks!

**Comment by shefsam1** [comment]
Same issue. Installing binary made no difference.

**Comment by Bushstar** [comment]
Check the debug.log in the datadir, on first run I only had the splash screen but the wallet was syncing in the background and eventually displayed the GUI. Leave it running headless for a while to see if it will appear.

The codebase is Bitcoin 0.8 which does not perform well compared to more modern codebases. It will soon be upgraded to the 0.13 codebase which will rectify a lot of performance issues.

**Comment by shefsam1** [comment]
Got it running... now received this:

![cannsyer](https://user-images.githubusercontent.com/22140139/42275900-c50961c0-7f5f-11e8-9a3f-93c51fa6ec22.JPG)

please advise

**Comment by Bushstar** [comment]
Possible wallet.dat corruption or the file is in use. Restart your computer and try again, if that does not succeed then either restore from backup or use the -salvagewallet startup param.

**Comment by shefsam1** [comment]
How do I get to the  -salvagewallet startup param without a cmd based cannabiscoin-client?

**Comment by Bushstar** [comment]
You can run it with Qt client, add it to the target field in your shortcut.

![Cannabiscoin](https://i.imgur.com/7oWQQaR.png)
