### ISSUE TITLE
Missing cannabiscoin-cli and cannabiscoind doesn't respond to getinfo commands

### ISSUE THREAD

**Issue by DarkIlluminatus** [cannabiscoindev/cannabiscoin420#2]
Exactly as in the title.  No readme information on a command line client.

**Comment by KonstiPation** [comment]
I can only agree, it'd be much better if the information was centralized in the Readme.

**Comment by Bushstar** [comment]
cannabiscoin-cli was never present in the Bitcoin 0.8 codebase on which Cannabiscoin is based hence the version 0.8. A new version of the client based on the 0.13 codebase will be created which will behave like modern versions of Bitcoin.
