### ISSUE TITLE
is the latest version for mac?

### ISSUE THREAD

**Issue by mbunal** [cannabiscoindev/cannabiscoin420#21]
i use this:
```
https://github.com/cannabiscoindev/cannabiscoin420/releases/download/v0.13.1/cannabiscoin-0.13.1-mac.dmg
```
I expected the version to be 0.13.1. but in the splash windows write 0.13.0. even in the about windows write
```
CannabisCoin Core version v0.13.0.0 (64-bit)
```

what is wrong?

**Comment by Bushstar** [comment]
Thanks for the report. The binary has now been updated, looks like the previous upload could technically have been 0.13.1 but with the previous version numbering. Just in case please download the new binary from the release tab, same name as the last one but this one will display 0.13.1.
