### ISSUE TITLE
CANN Bit rex offline?

### ISSUE THREAD

**Issue by IIPoliII** [cannabiscoindev/cannabiscoin420#22]
Hello,
The wallet of bitrex is still offline since really long when will it be putted back online?

**Comment by DarkIlluminatus** [comment]
This is closed recently, does that mean the issue has been resolved?

**Comment by IIPoliII** [comment]
No, but it was never solved in one yeah so I give up.

**Comment by DarkIlluminatus** [comment]
Too bad. The coin had so much potential

**Comment by jmcrn** [comment]
quick question how do i change dns seed i have a server name here but i mean the ip? is it necessary to swap both im assuming so?

**Comment by DarkIlluminatus** [comment]
Server name or IP is usually enough. You change it in %appdata%/cannabiscoin/cannabiscoin.conf if it doesn't exist you can create it.
