### ISSUE TITLE
no block source available

### ISSUE THREAD

**Issue by knoxcard** [cannabiscoindev/cannabiscoin420#4]
why am I seeing no block source available? I can't seem to initiate the blockchain download.

**Comment by knoxcard** [comment]
I am on Windows 10, by the way.  Downloaded the client wallet.

**Comment by DarkIlluminatus** [comment]
Same here.

**Comment by deisel16** [comment]
I have windows ten also and my cann wallet will not sync. I know you guys have been working on this for a while. Is there a support system here? i only put $50 in this so far, but would like to put a lot more. Please let us know what we can do.

**Comment by Horsetoothless** [comment]
would like to start mining this coin any information? got only simple peers list at the windows download does it have any mist release yet?

**Comment by deisel16** [comment]
I would love to mine it also. I am having trouble syncing my wallet. I says
no peers to connect to it. I would love some feed back if you find out
anything.

**Comment by sttaw** [comment]
1. Locate the exe used to launch your wallet. 
2. Create a file called cannabiscoin.conf
3. Add the following lines:
addnode=seed.cannabiscoin.net
addnode=seed2.cannabiscoin.net
addnode=seed3.cannabiscoin.net
addnode=seed4.cannabiscoin.net
addnode=seed5.cannabiscoin.net
addnode=seed6.cannabiscoin.net

The wallet will now sync.

**Comment by DarkIlluminatus** [comment]
Hooray! So happy to see this! I'll try it immediately

**Comment by DarkIlluminatus** [comment]
oop nevermind, those lines are already in the .conf and still not updating
the blockchain.

**Comment by DarkIlluminatus** [comment]
the blockchain snapshot and .conf settings in this file:
https://uploadfiles.io/zxh4w worked great!
Found it on the bitcointalk ANN thread

**Comment by DarkIlluminatus** [comment]
remember to set your own rpc pass and user
