### ISSUE TITLE
Avira detects tr/bitcoinminer.urdjy trojan after downloading Windows wallet

### ISSUE THREAD

**Issue by imkane** [cannabiscoindev/cannabiscoin420#6]
What's that all about?

I've never seen this happen with other digital currency clients.

**Comment by deisel16** [comment]
This concerns me. How do we remove this?

**Comment by imkane** [comment]
My solution was to not install it lol

**Comment by deisel16** [comment]
I didnt see this until it was to late. As soon as I did I turned my computer off and came in on my linux machine. Any ideas?

**Comment by Bushstar** [comment]
False positive, ignore it. I see this often with coins and mining software.

**Comment by deisel16** [comment]
How do I get my wallet to sync?
