### ISSUE TITLE
error in bignum.h when compiling

### ISSUE THREAD

**Issue by safocl** [cannabiscoindev/cannabiscoin420#7]
LC_ALL=C CXX=g++-4.3 CC=gcc-4.3 USE_UPNP=1 make -f makefile.unix 
/bin/sh ../share/genbuild.sh obj/build.h
g++-4.3 -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/safff/git/cannabiscoin420/src -I/home/safff/git/cannabiscoin420/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/home/safff/git/cannabiscoin420/src/leveldb/include -I/home/safff/git/cannabiscoin420/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/checkpoints.d -o obj/checkpoints.o checkpoints.cpp
In file included from main.h:8,
                 from checkpoints.cpp:10:
bignum.h:52: error: invalid use of incomplete type 'struct BIGNUM'
/usr/include/openssl/ossl_typ.h:80: error: forward declaration of 'struct BIGNUM'
bignum.h: In constructor 'CBigNum::CBigNum()':
bignum.h:56: error: 'BN_init' was not declared in this scope
bignum.h: In copy constructor 'CBigNum::CBigNum(const CBigNum&)':
bignum.h:61: error: 'BN_init' was not declared in this scope
bignum.h:62: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)'
bignum.h:64: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'void BN_clear_free(BIGNUM*)'
bignum.h: In member function 'CBigNum& CBigNum::operator=(const CBigNum&)':
bignum.h:71: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)'
bignum.h: In destructor 'CBigNum::~CBigNum()':
bignum.h:78: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'void BN_clear_free(BIGNUM*)'
bignum.h: In constructor 'CBigNum::CBigNum(signed char)':
bignum.h:82: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(short int)':
bignum.h:83: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(int)':
bignum.h:84: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(long int)':
bignum.h:85: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(int64)':
bignum.h:86: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(unsigned char)':
bignum.h:87: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(short unsigned int)':
bignum.h:88: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(unsigned int)':
bignum.h:89: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(long unsigned int)':
bignum.h:90: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(uint64)':
bignum.h:91: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(uint256)':
bignum.h:92: error: 'BN_init' was not declared in this scope
bignum.h: In constructor 'CBigNum::CBigNum(const std::vector<unsigned char, std::allocator<unsigned char> >&)':
bignum.h:96: error: 'BN_init' was not declared in this scope
bignum.h: In member function 'void CBigNum::setulong(long unsigned int)':
bignum.h:102: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_set_word(BIGNUM*, long unsigned int)'
bignum.h: In member function 'long unsigned int CBigNum::getulong() const':
bignum.h:108: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'long unsigned int BN_get_word(const BIGNUM*)'
bignum.h: In member function 'unsigned int CBigNum::getuint() const':
bignum.h:113: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'long unsigned int BN_get_word(const BIGNUM*)'
bignum.h: In member function 'int CBigNum::getint() const':
bignum.h:118: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'long unsigned int BN_get_word(const BIGNUM*)'
bignum.h:119: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_is_negative(const BIGNUM*)'
bignum.h: In member function 'void CBigNum::setint64(int64)':
bignum.h:167: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '3' to 'BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)'
bignum.h: In member function 'void CBigNum::setuint64(uint64)':
bignum.h:194: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '3' to 'BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)'
bignum.h: In member function 'void CBigNum::setuint256(uint256)':
bignum.h:222: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '3' to 'BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)'
bignum.h: In member function 'uint256 CBigNum::getuint256() const':
bignum.h:227: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_bn2mpi(const BIGNUM*, unsigned char*)'
bignum.h:231: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_bn2mpi(const BIGNUM*, unsigned char*)'
bignum.h: In member function 'void CBigNum::setvch(const std::vector<unsigned char, std::allocator<unsigned char> >&)':
bignum.h:252: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '3' to 'BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)'
bignum.h: In member function 'std::vector<unsigned char, std::allocator<unsigned char> > CBigNum::getvch() const':
bignum.h:257: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_bn2mpi(const BIGNUM*, unsigned char*)'
bignum.h:261: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_bn2mpi(const BIGNUM*, unsigned char*)'
bignum.h: In member function 'CBigNum& CBigNum::SetCompact(unsigned int)':
bignum.h:297: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_set_word(BIGNUM*, long unsigned int)'
bignum.h:301: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_set_word(BIGNUM*, long unsigned int)'
bignum.h:302: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_lshift(BIGNUM*, const BIGNUM*, int)'
bignum.h:304: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'void BN_set_negative(BIGNUM*, int)'
bignum.h: In member function 'unsigned int CBigNum::GetCompact() const':
bignum.h:310: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_num_bits(const BIGNUM*)'
bignum.h:313: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'long unsigned int BN_get_word(const BIGNUM*)'
bignum.h:317: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_rshift(BIGNUM*, const BIGNUM*, int)'
bignum.h:318: error: cannot convert 'CBigNum*' to 'const BIGNUM*' for argument '1' to 'long unsigned int BN_get_word(const BIGNUM*)'
bignum.h:328: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_is_negative(const BIGNUM*)'
bignum.h: In member function 'std::string CBigNum::ToString(int) const':
bignum.h:369: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'void BN_set_negative(BIGNUM*, int)'
bignum.h:372: error: cannot convert 'CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h:374: error: cannot convert 'CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h:376: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)'
bignum.h:382: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_is_negative(const BIGNUM*)'
bignum.h: In member function 'bool CBigNum::operator!() const':
bignum.h:415: error: cannot convert 'const CBigNum* const' to 'const BIGNUM*' for argument '1' to 'int BN_is_zero(const BIGNUM*)'
bignum.h: In member function 'CBigNum& CBigNum::operator+=(const CBigNum&)':
bignum.h:420: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)'
bignum.h: In member function 'CBigNum& CBigNum::operator*=(const CBigNum&)':
bignum.h:434: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)'
bignum.h: In member function 'CBigNum& CBigNum::operator<<=(unsigned int)':
bignum.h:453: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_lshift(BIGNUM*, const BIGNUM*, int)'
bignum.h: In member function 'CBigNum& CBigNum::operator>>=(unsigned int)':
bignum.h:464: error: cannot convert 'CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h:470: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_rshift(BIGNUM*, const BIGNUM*, int)'
bignum.h: In member function 'CBigNum& CBigNum::operator++()':
bignum.h:479: error: cannot convert 'CBigNum* const' to 'BIGNUM*' for argument '1' to 'int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)'
bignum.h: In member function 'CBigNum& CBigNum::operator--()':
bignum.h:496: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'const CBigNum operator+(const CBigNum&, const CBigNum&)':
bignum.h:521: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'const CBigNum operator-(const CBigNum&, const CBigNum&)':
bignum.h:529: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'const CBigNum operator-(const CBigNum&)':
bignum.h:537: error: cannot convert 'CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_is_negative(const BIGNUM*)'
bignum.h: In function 'const CBigNum operator*(const CBigNum&, const CBigNum&)':
bignum.h:545: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)'
bignum.h: In function 'const CBigNum operator/(const CBigNum&, const CBigNum&)':
bignum.h:554: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)'
bignum.h: In function 'const CBigNum operator%(const CBigNum&, const CBigNum&)':
bignum.h:563: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '2' to 'int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)'
bignum.h: In function 'const CBigNum operator<<(const CBigNum&, unsigned int)':
bignum.h:571: error: cannot convert 'CBigNum*' to 'BIGNUM*' for argument '1' to 'int BN_lshift(BIGNUM*, const BIGNUM*, int)'
bignum.h: In function 'bool operator==(const CBigNum&, const CBigNum&)':
bignum.h:583: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'bool operator!=(const CBigNum&, const CBigNum&)':
bignum.h:584: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'bool operator<=(const CBigNum&, const CBigNum&)':
bignum.h:585: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'bool operator>=(const CBigNum&, const CBigNum&)':
bignum.h:586: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'bool operator<(const CBigNum&, const CBigNum&)':
bignum.h:587: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
bignum.h: In function 'bool operator>(const CBigNum&, const CBigNum&)':
bignum.h:588: error: cannot convert 'const CBigNum*' to 'const BIGNUM*' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
make: *** [makefile.unix:179: obj/checkpoints.o] Error 1

**Comment by safocl** [comment]
my system is archlinux 
install GCC 4.3.6, openssl 1.1.0.f-1, Berkeley DB 4.8.30, boost 1.64, miniupnpc 2.0

**Comment by hanebuechenes** [comment]
Same problem to me. Any suggestions? Using debian stretch.

**Comment by Bushstar** [comment]
Use OpenSSL 1.0.1.

**Comment by movingelectrons** [comment]
this seems to still be broken, I am running debian 9 and I installed openssl 1.0.1 following the second suggestion here: https://unix.stackexchange.com/questions/419714/debian-9-old-version-of-openssl IE creating the /etc/apt/sources.list.d/jessie.list file...


Preconfiguring packages ...
Selecting previously unselected package libssl1.0.0:amd64.
(Reading database ... 269193 files and directories currently installed.)
Preparing to unpack .../libssl1.0.0_1.0.1t-1+deb8u8_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.1t-1+deb8u8) ...
Setting up libssl1.0.0:amd64 (1.0.1t-1+deb8u8) ...
jeromes@jtop ~/Downloads/cryptocoins/cannabiscoin420/src (master) $ make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
g++ -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/include -I/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o CannabisCoind leveldb/libleveldb.a obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/keystore.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/hash.o obj/bloom.o obj/noui.o obj/leveldb.o obj/txdb.o obj/cubehash.o obj/luffa.o obj/aes_helper.o obj/echo.o obj/shavite.o obj/simd.o obj/blake.o obj/bmw.o obj/groestl.o obj/jh.o obj/keccak.o obj/skein.o obj/checkpointsync.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/libleveldb.a /home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/leveldb/libmemenv.a
obj/key.o: In function `SetSecretBytes':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/key.cpp:152: undefined reference to `BN_init'
obj/init.o: In function `AppInit2(boost::thread_group&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/init.cpp:658: undefined reference to `SSLeay_version'
obj/init.o: In function `CBigNum::CBigNum(std::vector<unsigned char, std::allocator<unsigned char> > const&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:96: undefined reference to `BN_init'
obj/main.o: In function `CBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
obj/main.o: In function `CBigNum::CBigNum(unsigned int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:89: undefined reference to `BN_init'
obj/main.o: In function `CBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
obj/main.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: more undefined references to `BN_init' follow
obj/bitcoinrpc.o: In function `boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
/usr/include/boost/asio/ssl/impl/context.ipp:125: undefined reference to `SSLv23_method'
/usr/include/boost/asio/ssl/impl/context.ipp:125: undefined reference to `SSLv23_method'
obj/bitcoinrpc.o: In function `boost::asio::ssl::detail::openssl_init_base::do_init::~do_init()':
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:72: undefined reference to `CRYPTO_set_locking_callback'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:73: undefined reference to `ERR_free_strings'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:74: undefined reference to `EVP_cleanup'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:75: undefined reference to `CRYPTO_cleanup_all_ex_data'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:84: undefined reference to `SSL_COMP_free_compression_methods'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:92: undefined reference to `ENGINE_cleanup'
obj/bitcoinrpc.o: In function `CBigNum::CBigNum(int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
obj/bitcoinrpc.o: In function `CBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
obj/bitcoinrpc.o: In function `boost::asio::ssl::detail::openssl_init_base::do_init::~do_init()':
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:72: undefined reference to `CRYPTO_set_locking_callback'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:73: undefined reference to `ERR_free_strings'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:74: undefined reference to `EVP_cleanup'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:75: undefined reference to `CRYPTO_cleanup_all_ex_data'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:84: undefined reference to `SSL_COMP_free_compression_methods'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:92: undefined reference to `ENGINE_cleanup'
obj/bitcoinrpc.o: In function `boost::asio::ssl::detail::openssl_init_base::do_init::do_init()':
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:39: undefined reference to `SSL_library_init'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:40: undefined reference to `SSL_load_error_strings'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:41: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:44: undefined reference to `CRYPTO_num_locks'
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:47: undefined reference to `CRYPTO_set_locking_callback'
obj/rpcdump.o: In function `CBigNum::CBigNum(int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
obj/rpcdump.o: In function `CBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
obj/rpcdump.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: more undefined references to `BN_init' follow
obj/util.o: In function `CInit::~CInit()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:125: undefined reference to `CRYPTO_set_locking_callback'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:126: undefined reference to `CRYPTO_num_locks'
obj/util.o: In function `CInit::CInit()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:109: undefined reference to `CRYPTO_num_locks'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:110: undefined reference to `CRYPTO_num_locks'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/util.cpp:112: undefined reference to `CRYPTO_set_locking_callback'
obj/crypter.o: In function `CCrypter::Encrypt(std::vector<unsigned char, secure_allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:63: undefined reference to `EVP_CIPHER_CTX_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:67: undefined reference to `EVP_CIPHER_CTX_cleanup'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:67: undefined reference to `EVP_CIPHER_CTX_cleanup'
obj/crypter.o: In function `CCrypter::Decrypt(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, secure_allocator<unsigned char> >&)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:90: undefined reference to `EVP_CIPHER_CTX_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:94: undefined reference to `EVP_CIPHER_CTX_cleanup'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/crypter.cpp:94: undefined reference to `EVP_CIPHER_CTX_cleanup'
obj/rpcmining.o: In function `CBigNum::CBigNum()':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: undefined reference to `BN_init'
obj/rpcwallet.o: In function `CBigNum::CBigNum(int)':
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:84: undefined reference to `BN_init'
obj/rpcwallet.o:/home/jeromes/Downloads/cryptocoins/cannabiscoin420/src/bignum.h:56: more undefined references to `BN_init' follow
collect2: error: ld returned 1 exit status
makefile.unix:186: recipe for target 'CannabisCoind' failed
make: *** [CannabisCoind] Error 1
jeromes@jtop ~/Downloads/cryptocoins/cannabiscoin420/src (master) $
