### ISSUE TITLE
AVG blocking all attempts of downloading seed software.

### ISSUE THREAD

**Issue by Horsetoothless** [cannabiscoindev/cannabiscoin420#8]

**Comment by Horsetoothless** [comment]
what tomine has dropped this coin along with supernova mining pool.

CAN SOMEONE POST ANYTHING ELSE ABOUT COINS FUTURE PLANS?

**Comment by djspacedevil** [comment]
Comodo Anti Virus block it too.

**Comment by cannabiscoindev** [comment]
The AV warnings are false positives. They usually flag it, including wallets like Bitcoin Core as a coin stealer because it looks for a wallet.dat since it creates the file
